name: Pull Request Workflow

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  testRunner:
    name: Test ✨
    runs-on: ubuntu-8-cores
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Create temporary project clone
        run: |
          pwd
          folderName=$(echo "${PWD##*/}")
          rsync -r "$GITHUB_WORKSPACE" "copiedProject" 
          ls -F "copiedProject/$folderName"

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        id: testRunner
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}  
        with:
          packageMode: true
          unityVersion: "2022.3.17f1"
          projectPath: ./copiedProject/mona-wallet-unity
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          gitPrivateToken: ${{ secrets.TOKEN_ACCESS_UNITY_PACKAGES }}

      - uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: ${{ steps.testRunner.outputs.artifactsPath }}
